name: ci

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack
        run: corepack enable
        
      - name: Disable Global Cache Yarn PnP
        run: yarn config set enableGlobalCache false

      - name: Install Dependencies
        run: yarn

      - name: Run CI
        run: yarn ci
